fix: register missing codecs
dymensionxyz/rollapp-wasm pull request #138
Opened 2024-09-23 17:07 UTC by zale144

## Description

----

Closes #XXX

**All** items are required. Please add a note to the item if the item is not applicable and
please add links to any relevant follow-up issues.

PR review checkboxes:

I have...

- [ ]  Added a relevant changelog entry to the `Unreleased` section in `CHANGELOG.md`
- [ ]  Targeted PR against the correct branch
- [ ]  included the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Linked to the GitHub issue with discussion and accepted design
- [ ]  Targets only one GitHub issue
- [ ]  Wrote unit and integration tests
- [ ]  Wrote relevant migration scripts if necessary
- [ ]  All CI checks have passed
- [ ]  Added relevant `godoc` [comments](https://blog.golang.org/godoc-documenting-go-code)
- [ ]  Updated the scripts for local run, e.g genesis_config_commands.sh if the PR changes parameters
- [ ]  Add an issue in the [e2e-tests repo](https://github.com/dymensionxyz/e2e-tests) if necessary

SDK Checklist
- [ ] Import/Export Genesis
- [ ] Registered Invariants
- [ ] Registered Events
- [ ] Updated openapi.yaml
- [ ] No usage of go `map`
- [ ] No usage of `time.Now()`
- [ ] Used fixed point arithmetic and not float arithmetic
- [ ] Avoid panicking in Begin/End block as much as possible
- [ ] No unexpected math Overflow
- [ ] Used `sendCoin` and not `SendCoins`
- [ ] Out-of-block compute is bounded
- [ ] No serialized ID at the end of store keys
- [ ] UInt to byte conversion should use BigEndian

Full security checklist [here](https://www.faulttolerant.xyz/2024-01-16-cosmos-security-1/)

----;

For Reviewer:

- [ ]  Confirmed the correct [type prefix](https://github.com/commitizen/conventional-commit-types/blob/v3.0.0/index.json) in the PR title
- [ ]  Reviewers assigned
- [ ]  Confirmed all author checklist items have been addressed

---;

After reviewer approval:

- [ ]  In case the PR targets the main branch, PR should not be squash merge in order to keep meaningful git history.
- [ ]  In case the PR targets a release branch, PR must be rebased.

2024-09-26 13:08 UTC, mtsitrin requested changes

2024-09-26 13:46 UTC, mtsitrin commented on app/ante.go
> +func (o HandlerOptions) validate() error {
missing validation for used options:
`options.TxCounterStoreKey`
`options.SigGasConsumer`

2024-09-26 13:46 UTC, mtsitrin commented on app/app.go
> +				SigGasConsumer:  defaultSigVerificationGasConsumer,
why u needed local copy?
can't use
`SigGasConsumer:     evmosante.SigVerificationGasConsumer,`

as in rollapp-evm?

2024-09-26 14:15 UTC, mtsitrin commented
Few things that require additional research/validation:
* To support ledger with coin type 60 we need EIP712 support (at least for portal support)
* Will WASM frontend libs still work as expected? with ledger as well?

2024-10-09 12:19 UTC, mtsitrin approved these changes

2024-10-09 12:33 UTC, omritoptix approved these changes

2024-10-09 12:34 UTC, merged